import typer
from typing import Optional
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from rich.progress import Progress, SpinnerColumn, TextColumn
import os
import sys
from pathlib import Path
import subprocess

try:
    from app.main import revamp_project, revamp_and_implement
except ImportError:
    import sys
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from app.main import revamp_project, revamp_and_implement

app = typer.Typer(
    name="revamp",
    help="AI agent that transforms open-source GitHub projects into hackathon-winning solutions",
    add_completion=False,
)
console = Console()

@app.command()
def init(
    path: Path = typer.Argument(
        ".", help="Path where to initialize the project"
    ),
    name: str = typer.Option(
        "my-revamp-project", "--name", "-n", help="Name of the project"
    ),
):
    """
    Initialize a new revamp project structure.
    """
    console.print(Panel(f"🚀 Initializing new revamp project: [bold]{name}[/bold]", style="blue"))

    target_dir = path.resolve()
    if not target_dir.exists():
        target_dir.mkdir(parents=True)
    
    # Create directory structure
    (target_dir / "app").mkdir(exist_ok=True)
    (target_dir / "prompts").mkdir(exist_ok=True)
    (target_dir / "tests").mkdir(exist_ok=True)
    (target_dir / "tests" / "scenarios").mkdir(exist_ok=True)
    (target_dir / "tests" / "evaluations").mkdir(exist_ok=True)
    
    # Create basic files
    gitignore_content = """
.env
__pycache__/
*.pyc
.pytest_cache/
.venv/
    """.strip()
    
    env_example_content = """
OPENAI_API_KEY=your_openai_key
LANGWATCH_API_KEY=your_langwatch_key
FIRECRAWL_API_KEY=your_firecrawl_key
GITHUB_ACCESS_TOKEN=your_github_token
    """.strip()

    readme_content = f"""# {name}

Generated by Revamp Agent.

## Setup
1. `uv sync`
2. `cp .env.example .env` (and fill in keys)

## Usage
- `revamp analyze`
- `revamp generate`
    """.strip()
    
    pyproject_content = f"""[project]
name = "{name}"
version = "0.1.0"
description = "Revamp project generated by Revamp Agent"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.3.24",
    "typer>=0.15.1",
    "rich>=13.9.4",
    "python-dotenv>=1.0.1",
    "langwatch>=0.1.16",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
    """.strip()

    with (target_dir / ".gitignore").open("w") as f:
        f.write(gitignore_content)
        
    with (target_dir / ".env.example").open("w") as f:
        f.write(env_example_content)

    with (target_dir / "README.md").open("w") as f:
        f.write(readme_content)
        
    if not (target_dir / "pyproject.toml").exists():
        with (target_dir / "pyproject.toml").open("w") as f:
            f.write(pyproject_content)

    console.print(f"[green]✓[/green] Project structure created at {target_dir}")
    console.print(f"[yellow]![/yellow] Run `uv sync` to install dependencies.")


@app.command()
def analyze(
    github_url: Optional[str] = typer.Option(None, "--github", "-g", help="GitHub repository URL"),
    hackathon_url: Optional[str] = typer.Option(None, "--hackathon", "-h", help="Hackathon website URL"),
    topic: Optional[str] = typer.Option(None, "--topic", "-t", help="Search topic for discovery"),
    context: Optional[str] = typer.Option(None, "--context", "-c", help="Additional hackathon context"),
):
    """
    Analyze a codebase and hackathon to generate a revamp strategy.
    """
    console.print(Panel("🔍 Analyzing project and hackathon context...", style="cyan"))
    
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:
        task = progress.add_task(description="Running analysis agent...", total=None)
        
        result = revamp_project(
            github_url=github_url,
            hackathon_url=hackathon_url,
            hackathon_context=context,
            search_topic=topic
        )
    
    console.print(Panel(Markdown(result), title="Revamp Strategy", border_style="green"))


@app.command()
def generate(
    github_url: Optional[str] = typer.Option(None, "--github", "-g", help="GitHub repository URL"),
    hackathon_url: Optional[str] = typer.Option(None, "--hackathon", "-h", help="Hackathon website URL"),
    topic: Optional[str] = typer.Option(None, "--topic", "-t", help="Search topic for discovery"),
    context: Optional[str] = typer.Option(None, "--context", "-c", help="Additional hackathon context"),
    fork: bool = typer.Option(False, "--fork", "-f", help="Fork repository before implementing"),
    branch: str = typer.Option("hackathon-revamp", "--branch", "-b", help="Branch name for changes"),
):
    """
    Generate strategy and implement code changes.
    """
    console.print(Panel("🛠️ Generating strategy and implementing changes...", style="magenta"))

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:
        task = progress.add_task(description="Running coding agent...", total=None)
        
        result = revamp_and_implement(
            github_url=github_url,
            hackathon_url=hackathon_url,
            hackathon_context=context,
            search_topic=topic,
            implement_changes=True,
            fork_repo=fork,
            branch_name=branch
        )

    console.print(Panel(Markdown(result["strategy"]), title="Strategy", border_style="green"))
    
    if result.get("implementation"):
        console.print(Panel(Markdown(result["implementation"]), title="Implementation Report", border_style="yellow"))
    else:
        console.print("[red]Implementation failed or no changes were made.[/red]")


@app.command()
def test(
    command: Optional[str] = typer.Option(None, "--command", "-c", help="Custom test command to run"),
):
    """
    Run project tests.
    
    Automatically detects project type and runs appropriate test command:
    - Python: `uv run pytest` or `pytest`
    - Node.js: `npm test`
    - Rust: `cargo test`
    - Go: `go test ./...`
    
    You can override this detection with the --command option.
    """
    console.print(Panel("🧪 Running tests...", style="yellow"))
    
    test_cmd = []
    
    if command:
        test_cmd = command.split()
    else:
        # Auto-detect project type
        path = Path(".")
        if (path / "pyproject.toml").exists() or (path / "requirements.txt").exists():
            if (path / "uv.lock").exists():
                test_cmd = ["uv", "run", "pytest"]
            else:
                test_cmd = ["pytest"]
        elif (path / "package.json").exists():
            test_cmd = ["npm", "test"]
        elif (path / "Cargo.toml").exists():
            test_cmd = ["cargo", "test"]
        elif (path / "go.mod").exists():
            test_cmd = ["go", "test", "./..."]
        elif (path / "pom.xml").exists():
            test_cmd = ["mvn", "test"]
        else:
            console.print("[yellow]Could not detect project type. Defaulting to pytest.[/yellow]")
            test_cmd = ["pytest"]
            
    console.print(f"[dim]Executing: {' '.join(test_cmd)}[/dim]")

    try:
        subprocess.run(test_cmd, check=True)
        console.print("[green]Tests passed![/green]")
    except subprocess.CalledProcessError:
        console.print("[red]Tests failed![/red]")
        sys.exit(1)
    except FileNotFoundError:
        console.print(f"[red]Command not found: {test_cmd[0]}. Please ensure dependencies are installed.[/red]")
        sys.exit(1)


@app.command()
def interactive():
    """
    Interactive mode for guided revamp process.
    """
    console.print(Panel("🎯 Interactive Revamp Mode", style="cyan"))
    console.print("Let's build your hackathon strategy step by step!\n")
    
    # Step 1: Choose mode
    console.print("[bold]Step 1: Choose your starting point[/bold]")
    console.print("1. I have both GitHub repo and hackathon URLs")
    console.print("2. I have a GitHub repo, need to find hackathons")
    console.print("3. I have a hackathon, need to find projects")
    console.print("4. I want to discover both (surprise me!)")
    
    mode = typer.prompt("Choose option (1-4)", type=int)
    
    github_url = None
    hackathon_url = None
    topic = None
    
    if mode == 1:
        github_url = typer.prompt("GitHub repository URL")
        hackathon_url = typer.prompt("Hackathon website URL")
    elif mode == 2:
        github_url = typer.prompt("GitHub repository URL")
        topic = typer.prompt("Search topic (e.g., AI, web3, climate)", default="")
    elif mode == 3:
        hackathon_url = typer.prompt("Hackathon website URL")
    elif mode == 4:
        topic = typer.prompt("What topic interests you? (e.g., AI, web3, climate)")
    
    # Step 2: Implementation options
    console.print("\n[bold]Step 2: Implementation options[/bold]")
    implement = typer.confirm("Do you want to automatically implement code changes?", default=False)
    fork = False
    branch = "hackathon-revamp"
    
    if implement:
        fork = typer.confirm("Fork the repository before making changes?", default=True)
        branch = typer.prompt("Branch name for changes", default="hackathon-revamp")
    
    # Step 3: Execute
    console.print(f"\n[bold]Step 3: Running revamp...[/bold]")
    
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:
        task = progress.add_task(description="Generating strategy...", total=None)
        
        if implement:
            result = revamp_and_implement(
                github_url=github_url,
                hackathon_url=hackathon_url,
                search_topic=topic,
                implement_changes=True,
                fork_repo=fork,
                branch_name=branch
            )
            console.print(Panel(Markdown(result["strategy"]), title="Strategy", border_style="green"))
            if result.get("implementation"):
                console.print(Panel(Markdown(result["implementation"]), title="Implementation", border_style="yellow"))
        else:
            result = revamp_project(
                github_url=github_url,
                hackathon_url=hackathon_url,
                search_topic=topic
            )
            console.print(Panel(Markdown(result), title="Revamp Strategy", border_style="green"))

@app.command()
def web():
    """
    Start the web interface.
    """
    console.print(Panel("🌐 Starting Web Interface", style="blue"))
    console.print("Opening web interface at http://localhost:8000")
    console.print("Press Ctrl+C to stop\n")
    
    try:
        import subprocess
        subprocess.run(["uv", "run", "python", "app/web_interface.py"], check=True)
    except KeyboardInterrupt:
        console.print("\n[yellow]Web interface stopped.[/yellow]")
    except subprocess.CalledProcessError:
        console.print("[red]Failed to start web interface. Check your setup.[/red]")

@app.command()
def setup():
    """
    Run the interactive setup wizard.
    """
    console.print(Panel("⚙️ Setup Wizard", style="green"))
    
    try:
        import subprocess
        subprocess.run(["python", "setup_wizard.py"], check=True)
    except subprocess.CalledProcessError:
        console.print("[red]Setup failed. Please check the error messages above.[/red]")

@app.command()
def examples():
    """
    Show usage examples and tutorials.
    """
    console.print(Panel("📚 Revamp Agent Examples", style="magenta"))
    
    examples_text = """
## Quick Examples

### 1. Basic Analysis
```bash
revamp analyze --github https://github.com/user/repo --hackathon https://hackathon-site.com
```

### 2. Auto-Discovery
```bash
revamp analyze --topic "AI"
```

### 3. Full Implementation
```bash
revamp generate --github https://github.com/user/repo --hackathon https://hackathon-site.com --fork
```

### 4. Interactive Mode
```bash
revamp interactive
```

### 5. Web Interface
```bash
revamp web
```

## Popular Topics
- **AI/ML**: artificial intelligence, machine learning, deep learning
- **Web3**: blockchain, cryptocurrency, DeFi, NFT
- **Climate**: sustainability, environment, carbon tracking
- **Healthcare**: medical, health tech, telemedicine
- **Fintech**: payments, banking, financial services
- **IoT**: internet of things, sensors, smart devices

## Pro Tips
- Use `--fork` to safely make changes to repositories
- Try discovery mode when you're not sure what to build
- The web interface is great for non-technical team members
- Interactive mode guides you through the entire process
    """
    
    console.print(Markdown(examples_text))

@app.command()
def deploy():
    """
    Deploy using Docker or cloud platforms.
    """
    console.print(Panel("🚀 Deployment Options", style="blue"))
    
    console.print("[bold]Available deployment methods:[/bold]")
    console.print("1. Docker Compose (local)")
    console.print("2. Railway (cloud)")
    console.print("3. Render (cloud)")
    console.print("4. Heroku (cloud)")
    
    method = typer.prompt("Choose deployment method (1-4)", type=int)
    
    if method == 1:
        console.print("\n[bold]Docker Compose Deployment:[/bold]")
        console.print("1. Make sure Docker is installed")
        console.print("2. Copy your .env file to the project root")
        console.print("3. Run: docker-compose up -d")
        console.print("4. Access at http://localhost:8000")
        
        if typer.confirm("Start Docker deployment now?"):
            try:
                subprocess.run(["docker-compose", "up", "-d"], check=True)
                console.print("[green]✓[/green] Deployment started!")
            except subprocess.CalledProcessError:
                console.print("[red]Deployment failed. Check Docker installation.[/red]")
    
    elif method == 2:
        console.print("\n[bold]Railway Deployment:[/bold]")
        console.print("1. Install Railway CLI: npm install -g @railway/cli")
        console.print("2. Login: railway login")
        console.print("3. Deploy: railway up")
        console.print("4. Set environment variables in Railway dashboard")
    
    elif method == 3:
        console.print("\n[bold]Render Deployment:[/bold]")
        console.print("1. Connect your GitHub repo to Render")
        console.print("2. Choose 'Web Service'")
        console.print("3. Build command: uv sync")
        console.print("4. Start command: uv run python app/web_interface.py")
        console.print("5. Add environment variables in Render dashboard")
    
    elif method == 4:
        console.print("\n[bold]Heroku Deployment:[/bold]")
        console.print("1. Install Heroku CLI")
        console.print("2. heroku create your-app-name")
        console.print("3. git push heroku main")
        console.print("4. heroku config:set OPENAI_API_KEY=your_key")
        console.print("5. Add other environment variables as needed")


if __name__ == "__main__":
    app()